version: '3.0'

services:
  
  es_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    ports:
      - "${es_container_port}:${es_dockerhost_port}"
    container_name: "${operation_name}_es_db"
    volumes:
      - "esdata:${volume_path}elasticsearch/data"
  
  get_data:
    depends_on:
      - es_db
    env_file:
      - ./$env_file
    image: "${docker_image_host}/${image_path}/get_data"
    container_name: "${operation_name}_get_data"

  worker:
    depends_on:
      - es_db
      - get_data
    env_file:
      - ./$env_file
    image: "${docker_image_host}/${image_path}/worker"
    container_name: "${operation_name}_worker"

volumes:
  esdata:
    driver: local