version: '3.7'

services:
  db:
    image: postgres:11.2-alpine
    env_file:
      - "dev.env"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
      
  web:
    build: ./worker
    ports:
      - "8001:8001"
    env_file:
      - "dev.env"
    depends_on:
      - db
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9000:80"
    env_file:
      - "dev.env"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  pgdata:
    driver: local
    name: pgdata
