version: '3.7'

services:
  
  es_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    ports:
      - 9200:9200
    container_name: "${operation_name}_es_db"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  
  get_data:
    depends_on:
      - es_db
    env_file:
      - ./$env_file
    build:
      context: .
      dockerfile: ./get_data/Dockerfile
    container_name: "${operation_name}_get_data"
<<<<<<< HEAD
=======
    stdin_open: true #
    tty: true #
>>>>>>> 2a5c0de7750ec1dddcde9ff35ee40e771d0cc256

  worker:
    depends_on:
      - es_db
      - get_data
    env_file:
      - ./$env_file
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: "${operation_name}_worker"

volumes:
  esdata:
    driver: local