version: '3'

services:
  es_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    ports:
      - 9200:9200
    container_name: "${operation_name}_es_db"
    volumes:
      - esdata:/usr/share/elasticsearch/data
#  worker:
#    image:
#    ports:
#      9200:9200
#      80:80 #(ou 8080:80 ou 80:8080 ?)
#    container_name: "$operation_name"
#    environment: #verificar sintaxe
#      - $strategy
#      - $state
#      - $market
#      - $stock_exchange

volumes:
  esdata:
    driver: local