version: '3'

services:
  es_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    ports:
      - 9200:9200
    container_name: "$es_db_name"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local