version: '3.7'

services:
  db:
    image: postgres:11.2-alpine
    env_file:
      - "../$env_file"
    ports:
      - "$DB_PORT:5432"
    volumes:
      - dev_pg:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "$PGADMIN_PORT:80"
    env_file:
      - "../$env_file"
    volumes:
      - pgadmin:$PG_ADMIN_DATA_DIR
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
  
volumes:
  dev_pg:
    driver: local
    name: dev_pg
  pgadmin:
    driver: local
    name: pgadmin